on:
  push:
    branches: [master]
    paths: 
      - 'lib/**'
      - 'backend/version'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: jdx/mise-action@v2

    - name: create .npmrc
      run: |
        registry=https://registry.npmjs.org/ > ~/.npmrc

    - name: Update Version
      run: |
        echo -n "-$(git rev-parse --short HEAD)" >> backend/version && \
        node util/versioning.mjs update package.json lib/package.json

    - name: Install, Build & Publish
      working-directory: lib
      run: |
        pnpm ci && \
        pnpm build && \
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          pnpm publish --no-git-checks --tag latest
        else
          pnpm publish --no-git-checks --tag prerelease
        fi
