on:
  push:
    branches: [master]
    paths: 
      - 'lib/**'
      - 'backend/version'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - uses: jdx/mise-action@v4

    - name: Update npm
      run: npm install -g npm@latest

    - name: Update Version
      run: |
        if [[ "${{ github.ref_type }}" != "tag" ]]; then
          echo -n "-$(git rev-parse --short HEAD)" >> backend/version
        fi
        node util/versioning.mjs update package.json lib/package.json

    - name: Install & Build
      working-directory: lib
      run: pnpm install && pnpm build

    - name: Publish
      working-directory: lib
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          npm publish --provenance --access public --tag latest
        else
          npm publish --provenance --access public --tag prerelease
        fi
